//! Typed Rust client generation from SPEL IDL.

use spel_framework_core::idl::*;
use std::collections::HashSet;
use std::fmt::Write;
use crate::util::*;

/// Generate a typed Rust client module from an IDL.
pub fn generate_client(idl: &SpelIdl) -> Result<String, String> {
    let mut out = String::new();
    let program_pascal = pascal_case(&idl.name);

    // Header
    writeln!(out, "//! Auto-generated client for the {} program.", idl.name).unwrap();
    writeln!(out, "//! Generated by spel-client-gen from IDL v{}.", idl.version).unwrap();
    writeln!(out, "//! DO NOT EDIT — regenerate from IDL instead.").unwrap();
    writeln!(out).unwrap();

    // Imports
    writeln!(out, "use sequencer_service_rpc::RpcClient as _;").unwrap();
    writeln!(out, "use nssa::{{").unwrap();
    writeln!(out, "    AccountId, ProgramId, PublicTransaction,").unwrap();
    writeln!(out, "    public_transaction::{{Message, WitnessSet}},").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out, "use borsh::BorshDeserialize;").unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out, "use wallet::WalletCore;").unwrap();
    writeln!(out).unwrap();

    // Parse helpers
    writeln!(out, "/// Parse a hex string into ProgramId [u32; 8] (little-endian byte order).").unwrap();
    writeln!(out, "pub fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() != 64 {{").unwrap();
    writeln!(out, "        return Err(format!(\"program_id hex must be 64 chars, got {{}}\", s.len()));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "    let mut pid = [0u32; 8];").unwrap();
    writeln!(out, "    for (i, chunk) in bytes.chunks(4).enumerate() {{").unwrap();
    writeln!(out, "        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Ok(pid)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // --- Standalone PDA computation helpers ---
    let pda_helpers = collect_pda_helpers(idl);
    for helper in &pda_helpers {
        writeln!(out, "/// Compute PDA for the `{}` account.", helper.account_name).unwrap();
        write!(out, "pub fn compute_{}_pda(program_id: &ProgramId", helper.account_name).unwrap();
        for (pname, pty) in &helper.params {
            write!(out, ", {}: {}", pname, pty).unwrap();
        }
        writeln!(out, ") -> AccountId {{").unwrap();
        for binding in &helper.let_bindings {
            writeln!(out, "    {}", binding).unwrap();
        }
        writeln!(out, "    spel_framework_core::pda::compute_pda(program_id, &[").unwrap();
        for expr in &helper.seed_exprs {
            writeln!(out, "        {},", expr).unwrap();
        }
        writeln!(out, "    ])").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // Instruction enum
    writeln!(out, "#[derive(Clone, Debug, Serialize, Deserialize)]").unwrap();
    writeln!(out, "pub enum {}Instruction {{", program_pascal).unwrap();
    for ix in &idl.instructions {
        let variant = pascal_case(&ix.name);
        if ix.args.is_empty() {
            writeln!(out, "    {},", variant).unwrap();
        } else {
            writeln!(out, "    {} {{", variant).unwrap();
            for arg in &ix.args {
                writeln!(out, "        {}: {},", rust_ident(&arg.name), idl_type_to_rust(&arg.type_)).unwrap();
            }
            writeln!(out, "    }},").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-instruction account structs
    for ix in &idl.instructions {
        let accounts_name = format!("{}Accounts", pascal_case(&ix.name));
        writeln!(out, "pub struct {} {{", accounts_name).unwrap();
        for acc in &ix.accounts {
            if acc.rest {
                writeln!(out, "    pub {}: Vec<AccountId>,", rust_ident(&acc.name)).unwrap();
            } else {
                writeln!(out, "    pub {}: AccountId,", rust_ident(&acc.name)).unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // Client struct
    writeln!(out, "pub struct {}Client<'w> {{", program_pascal).unwrap();
    writeln!(out, "    pub wallet: &'w WalletCore,").unwrap();
    writeln!(out, "    pub program_id: ProgramId,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl<'w> {}Client<'w> {{", program_pascal).unwrap();
    writeln!(out, "    pub fn new(wallet: &'w WalletCore, program_id: ProgramId) -> Self {{").unwrap();
    writeln!(out, "        Self {{ wallet, program_id }}").unwrap();
    writeln!(out, "    }}").unwrap();

    for ix in &idl.instructions {
        let method = rust_ident(&ix.name);
        let accounts_name = format!("{}Accounts", pascal_case(&ix.name));
        let variant = pascal_case(&ix.name);

        writeln!(out).unwrap();
        write!(out, "    pub async fn {}(\n        &self,\n        accounts: {}", method, accounts_name).unwrap();
        for arg in &ix.args {
            write!(out, ",\n        {}: {}", rust_ident(&arg.name), idl_type_to_rust(&arg.type_)).unwrap();
        }
        writeln!(out, ",\n    ) -> Result<String, String> {{").unwrap();

        // Build instruction
        if ix.args.is_empty() {
            writeln!(out, "        let instruction = {}Instruction::{};", program_pascal, variant).unwrap();
        } else {
            writeln!(out, "        let instruction = {}Instruction::{} {{", program_pascal, variant).unwrap();
            for arg in &ix.args {
                writeln!(out, "            {},", rust_ident(&arg.name)).unwrap();
            }
            writeln!(out, "        }};").unwrap();
        }

        // Account IDs
        writeln!(out, "        let mut account_ids: Vec<AccountId> = vec![").unwrap();
        for acc in ix.accounts.iter().filter(|a| !a.rest) {
            writeln!(out, "            accounts.{},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "        ];").unwrap();
        for acc in ix.accounts.iter().filter(|a| a.rest) {
            writeln!(out, "        account_ids.extend_from_slice(&accounts.{});", rust_ident(&acc.name)).unwrap();
        }

        // Signers
        let signers: Vec<_> = ix.accounts.iter().filter(|a| a.signer).collect();
        writeln!(out, "        let signer_ids: Vec<AccountId> = vec![").unwrap();
        for s in &signers {
            writeln!(out, "            accounts.{},", rust_ident(&s.name)).unwrap();
        }
        writeln!(out, "        ];").unwrap();
        writeln!(out, "        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"nonces: {{}}\", e))?;").unwrap();
        writeln!(out, "        let mut signing_keys = Vec::new();").unwrap();
        writeln!(out, "        for sid in &signer_ids {{").unwrap();
        writeln!(out, "            let key = self.wallet.storage().user_data").unwrap();
        writeln!(out, "                .get_pub_account_signing_key(*sid)").unwrap();
        writeln!(out, "                .ok_or_else(|| format!(\"signing key not found for {{}}\", sid))?;").unwrap();
        writeln!(out, "            signing_keys.push(key);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"message: {{:?}}\", e))?;").unwrap();
        writeln!(out, "        let witness_set = WitnessSet::for_message(&message, &signing_keys);").unwrap();
        writeln!(out, "        let tx = PublicTransaction::new(message, witness_set);").unwrap();
        writeln!(out, "        let response = self.wallet.sequencer_client.send_transaction(common::transaction::NSSATransaction::Public(tx)).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"submit: {{}}\", e))?;").unwrap();
        writeln!(out, "        Ok(hex::encode(response.0))").unwrap();
        writeln!(out, "    }}").unwrap();
    }

    // --- State fetch+deserialize helpers ---
    for helper in &pda_helpers {
        writeln!(out).unwrap();
        writeln!(out, "    /// Fetch and deserialize the `{}` account state.", helper.account_name).unwrap();
        write!(out, "    pub async fn fetch_{}<T: BorshDeserialize>(\n        &self", helper.account_name).unwrap();
        for (pname, pty) in &helper.params {
            write!(out, ",\n        {}: {}", pname, pty).unwrap();
        }
        writeln!(out, ",\n    ) -> Result<T, String> {{").unwrap();
        write!(out, "        let account_id = compute_{}_pda(&self.program_id", helper.account_name).unwrap();
        for (pname, _) in &helper.params {
            write!(out, ", {}", pname).unwrap();
        }
        writeln!(out, ");").unwrap();
        writeln!(out, "        let account = self.wallet.sequencer_client").unwrap();
        writeln!(out, "            .get_account(account_id).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"fetch {}: {{}}\", e))?;", helper.account_name).unwrap();
        writeln!(out, "        T::try_from_slice(&account.data)").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"deserialize {}: {{}}\", e))", helper.account_name).unwrap();
        writeln!(out, "    }}").unwrap();
    }

    writeln!(out, "}}").unwrap();
    Ok(out)
}

/// Information about a PDA helper to generate.
struct PdaHelper {
    account_name: String,
    params: Vec<(String, String)>,  // (param_name, param_type) for non-const seeds
    let_bindings: Vec<String>,      // let bindings needed before compute_pda call
    seed_exprs: Vec<String>,        // seed slice expressions for compute_pda
}

/// Collect unique PDA accounts across all instructions, deduplicating by account name.
fn collect_pda_helpers(idl: &SpelIdl) -> Vec<PdaHelper> {
    let mut seen = HashSet::new();
    let mut helpers = Vec::new();

    for ix in &idl.instructions {
        for acc in &ix.accounts {
            if let Some(pda) = &acc.pda {
                let account_name = snake_case(&acc.name);
                if !seen.insert(account_name.clone()) {
                    continue;
                }

                let mut params = Vec::new();
                let mut let_bindings = Vec::new();
                let mut seed_exprs = Vec::new();

                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { value } => {
                            let var = format!("seed_const_{}", let_bindings.len());
                            let_bindings.push(format!(
                                "let {} = spel_framework_core::pda::seed_from_str(\"{}\");",
                                var, value
                            ));
                            seed_exprs.push(format!("&{}", var));
                        }
                        IdlSeed::Account { path } => {
                            let name = snake_case(path);
                            params.push((name.clone(), "&AccountId".to_string()));
                            seed_exprs.push(format!("{}.value()", name));
                        }
                        IdlSeed::Arg { path } => {
                            let name = snake_case(path);
                            let ty = ix.args.iter()
                                .find(|a| a.name == *path)
                                .map(|a| idl_type_to_rust(&a.type_))
                                .unwrap_or_else(|| "String".to_string());

                            let (param_ty, binding, expr) = seed_arg_codegen(&name, &ty);
                            params.push((name, param_ty));
                            if let Some(b) = binding {
                                let_bindings.push(b);
                            }
                            seed_exprs.push(expr);
                        }
                    }
                }

                helpers.push(PdaHelper {
                    account_name,
                    params,
                    let_bindings,
                    seed_exprs,
                });
            }
        }
    }
    helpers
}

/// Generate codegen expressions for a seed argument based on its Rust type.
/// Returns (param_type, optional_let_binding, seed_expression).
pub(crate) fn seed_arg_codegen(name: &str, rust_type: &str) -> (String, Option<String>, String) {
    match rust_type {
        "AccountId" => (
            "&AccountId".to_string(),
            None,
            format!("{}.value()", name),
        ),
        "[u8; 32]" | "[u8;32]" => (
            format!("&{}", rust_type),
            None,
            format!("{}", name),
        ),
        "ProgramId" | "[u32; 8]" | "[u32;8]" => (
            "&ProgramId".to_string(),
            Some(format!("let {name}_seed: [u8; 32] = {name}.iter().flat_map(|w| w.to_le_bytes()).collect::<Vec<_>>().try_into().unwrap();")),
            format!("&{name}_seed"),
        ),
        "u64" | "u32" | "u16" | "u8" | "u128" | "i64" | "i32" | "i16" | "i8" | "i128" => (
            rust_type.to_string(),
            Some(format!("let {name}_be = {name}.to_be_bytes();\n    let mut {name}_seed = [0u8; 32];\n    {name}_seed[..{name}_be.len()].copy_from_slice(&{name}_be);")),
            format!("&{name}_seed"),
        ),
        "String" => (
            "&str".to_string(),
            Some(format!("let {name}_seed = spel_framework_core::pda::seed_from_str({name});")),
            format!("&{name}_seed"),
        ),
        _ => (
            format!("&{}", rust_type),
            Some(format!("let {name}_seed = spel_framework_core::pda::seed_from_str(&{name}.to_string());")),
            format!("&{name}_seed"),
        ),
    }
}
