//! C FFI wrapper generation from SPEL IDL.
//!
//! Generates `extern "C"` functions that accept JSON strings and return JSON strings.
//! The generated FFI includes full transaction building via `wallet::WalletCore`.
//!
//! If the IDL has `instruction_type` set (e.g. `"multisig_core::Instruction"`),
//! the generated code imports and uses that type directly — ensuring correct
//! serde/borsh representation when the instruction is sent to the zkVM guest.
//!
//! If `instruction_type` is absent, a local enum is generated with
//! `#[derive(Serialize, Deserialize)]` which works for simple programs.

use spel_framework_core::idl::*;
use std::fmt::Write;
use crate::util::*;

/// Generate C FFI wrapper source code from an IDL.
pub fn generate_ffi(idl: &SpelIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let local_enum = pascal_case(&idl.name) + "Instruction";

    // When instruction_type is set, we import it as `ProgramInstruction`.
    // When absent, we generate a local enum named `{Program}Instruction`.
    let instr_type = if idl.instruction_type.is_some() {
        "ProgramInstruction".to_string()
    } else {
        local_enum.clone()
    };

    // Header
    writeln!(out, "//! Auto-generated C FFI for the {} program.", idl.name).unwrap();
    writeln!(out, "//! Generated by spel-client-gen. DO NOT EDIT.").unwrap();
    writeln!(out, "//!").unwrap();
    writeln!(out, "//! Required JSON fields for every instruction call:").unwrap();
    writeln!(out, "//!   - `wallet_path`: path to NSSA wallet directory").unwrap();
    writeln!(out, "//!   - `sequencer_url`: e.g. \"http://127.0.0.1:3040\"").unwrap();
    writeln!(out, "//!   - `program_id_hex`: 64-char hex string identifying the program").unwrap();
    writeln!(out).unwrap();

    // Imports
    writeln!(out, "use std::ffi::{{CStr, CString}};").unwrap();
    writeln!(out, "use std::os::raw::c_char;").unwrap();
    writeln!(out, "use serde_json::{{Value, json}};").unwrap();
    writeln!(out, "use sha2::{{Sha256, Digest}};").unwrap();
    writeln!(out, "use nssa::{{AccountId, ProgramId, PublicTransaction}};").unwrap();
    writeln!(out, "use nssa::public_transaction::{{Message, WitnessSet}};").unwrap();
    writeln!(out, "use sequencer_service_rpc::RpcClient as _;").unwrap();
    writeln!(out, "use wallet::WalletCore;").unwrap();
    writeln!(out, "use std::panic::UnwindSafe;").unwrap();

    // Import or generate instruction type
    if let Some(ref itype) = idl.instruction_type {
        writeln!(out, "use {} as ProgramInstruction;", itype).unwrap();
    } else {
        // Generate local instruction enum
        writeln!(out, "use serde::{{Serialize, Deserialize}};").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(out, "pub enum {local_enum} {{").unwrap();
        for ix in &idl.instructions {
            let variant = pascal_case(&ix.name);
            if ix.args.is_empty() {
                writeln!(out, "    {variant},").unwrap();
            } else {
                writeln!(out, "    {variant} {{").unwrap();
                for arg in &ix.args {
                    let name = rust_ident(&arg.name);
                    let ty = idl_type_to_rust(&arg.type_);
                    writeln!(out, "        {name}: {ty},").unwrap();
                }
                writeln!(out, "    }},").unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
    }
    writeln!(out).unwrap();

    // Helper fns
    writeln!(out, "fn cstr_to_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {{").unwrap();
    writeln!(out, "    if ptr.is_null() {{ return Err(\"null pointer\".into()); }}").unwrap();
    writeln!(out, "    unsafe {{ CStr::from_ptr(ptr) }}.to_str().map_err(|e| format!(\"invalid UTF-8: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn to_cstring(s: String) -> *mut c_char {{").unwrap();
    writeln!(out, "    CString::new(s).unwrap_or_else(|_|").unwrap();
    writeln!(out, "        CString::new(r#\"{{\"success\":false,\"error\":\"null byte\"}}\"#).unwrap()").unwrap();
    writeln!(out, "    ).into_raw()").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn error_json(msg: &str) -> *mut c_char {{").unwrap();
    writeln!(out, "    let v = serde_json::json!(msg).to_string();").unwrap();
    writeln!(out, "    let body = format!(\"{{{{\\\"success\\\":false,\\\"error\\\":{{}}}}}}\", v);").unwrap();
    writeln!(out, "    to_cstring(body)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Panic-safe FFI wrapper — catches panics and returns error JSON instead of aborting.
    writeln!(out, "fn ffi_call(f: impl FnOnce() -> Result<String, String> + UnwindSafe) -> *mut c_char {{").unwrap();
    writeln!(out, "    match std::panic::catch_unwind(f) {{").unwrap();
    writeln!(out, "        Ok(Ok(r))  => to_cstring(r),").unwrap();
    writeln!(out, "        Ok(Err(e)) => error_json(&e),").unwrap();
    writeln!(out, "        Err(_)     => error_json(\"internal panic in FFI\"),").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // PDA helper
    writeln!(out, "fn compute_pda(seeds: &[&[u8]]) -> AccountId {{").unwrap();
    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "    for seed in seeds {{").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        let len = seed.len().min(32);").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "        hasher.update(&padded);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let hash: [u8; 32] = hasher.finalize().into();").unwrap();
    writeln!(out, "    AccountId::new(hash)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_program_id_hex
    writeln!(out, "fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() != 64 {{ return Err(format!(\"program_id hex must be 64 chars, got {{}}\", s.len())); }}").unwrap();
    writeln!(out, "    let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "    let mut pid = [0u32; 8];").unwrap();
    writeln!(out, "    for (i, chunk) in bytes.chunks(4).enumerate() {{").unwrap();
    writeln!(out, "        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Ok(pid)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_program_id (alias for ProgramId-typed args)
    writeln!(out, "fn parse_program_id(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    parse_program_id_hex(s)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_account_id
    writeln!(out, "fn parse_account_id(s: &str) -> Result<AccountId, String> {{").unwrap();
    writeln!(out, "    if let Ok(id) = s.parse() {{ return Ok(id); }}").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() == 64 {{").unwrap();
    writeln!(out, "        let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32]; arr.copy_from_slice(&bytes);").unwrap();
    writeln!(out, "        return Ok(AccountId::new(arr));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Err(format!(\"invalid AccountId: {{}}\", s))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // init_wallet
    writeln!(out, "fn init_wallet(v: &Value) -> Result<WalletCore, String> {{").unwrap();
    writeln!(out, "    if let Some(p) = v[\"wallet_path\"].as_str() {{").unwrap();
    writeln!(out, "        std::env::set_var(\"NSSA_WALLET_HOME_DIR\", p);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    WalletCore::from_env().map_err(|e| format!(\"wallet init: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-instruction FFI functions
    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        let variant = pascal_case(&ix.name);
        let signer_accounts: Vec<&IdlAccountItem> = ix.accounts.iter().filter(|a| a.signer).collect();

        writeln!(out, "/// FFI: {} instruction.", ix.name).unwrap();
        writeln!(out, "#[no_mangle]").unwrap();
        writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
        writeln!(out, "    let args = match cstr_to_str(args_json) {{").unwrap();
        writeln!(out, "        Ok(s) => s, Err(e) => return error_json(&e),").unwrap();
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    ffi_call(move || {fn_name}_impl(args))").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "fn {fn_name}_impl(args: &str) -> Result<String, String> {{").unwrap();
        writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
        writeln!(out, "    let program_id = parse_program_id_hex(v[\"program_id_hex\"].as_str().ok_or(\"missing program_id_hex\")?)?;").unwrap();
        writeln!(out, "    let wallet = init_wallet(&v)?;").unwrap();
        writeln!(out).unwrap();

        // Parse args
        for arg in &ix.args {
            let name = rust_ident(&arg.name);
            let parse_expr = idl_type_to_json_parse(&arg.type_, &format!("v[\"{}\"]", arg.name));
            writeln!(out, "    let {name} = {parse_expr};").unwrap();
        }
        writeln!(out).unwrap();

        // Build a type map for PDA seed arg type checks (same pattern as generate_pda_helpers)
        let param_type_map: std::collections::HashMap<String, String> = ix.args.iter()
            .map(|a| (rust_ident(&a.name), idl_type_to_rust(&a.type_)))
            .collect();

        // Resolve accounts
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if acc.rest {
                // rest accounts parsed from JSON array
                writeln!(out, "    let {name}: Vec<AccountId> = v[\"{}\"].as_array()", acc.name).unwrap();
                writeln!(out, "        .ok_or(\"missing {}\")?", acc.name).unwrap();
                writeln!(out, "        .iter().map(|a| parse_account_id(a.as_str().ok_or(\"expected string\")?)).collect::<Result<Vec<_>,_>>()?;").unwrap();
            } else if let Some(pda) = &acc.pda {
                writeln!(out, "    let {name} = compute_pda(&[").unwrap();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { value } => writeln!(out, "        b\"{value}\",").unwrap(),
                        IdlSeed::Account { path } => writeln!(out, "        {}.as_ref(),", rust_ident(path)).unwrap(),
                        IdlSeed::Arg { path } => {
                            let pname = rust_ident(path);
                            let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                            if arg_ty == "u64" {
                                writeln!(out, "        &{pname}.to_le_bytes(),").unwrap();
                            } else {
                                writeln!(out, "        &{pname} as &[u8],").unwrap();
                            }
                        }
                    }
                }
                writeln!(out, "    ]);").unwrap();
            } else {
                writeln!(out, "    let {name} = parse_account_id(v[\"{}\"].as_str().ok_or(\"missing {}\")?)?;",
                    acc.name, acc.name).unwrap();
            }
        }
        writeln!(out).unwrap();

        // Build account_ids vec (non-rest accounts first, then rest)
        writeln!(out, "    let mut account_ids: Vec<AccountId> = vec![").unwrap();
        for acc in ix.accounts.iter().filter(|a| !a.rest) {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        for acc in ix.accounts.iter().filter(|a| a.rest) {
            writeln!(out, "    account_ids.extend({});", rust_ident(&acc.name)).unwrap();
        }

        // Signer IDs
        writeln!(out, "    let signer_ids: Vec<AccountId> = vec![").unwrap();
        for acc in &signer_accounts {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        writeln!(out).unwrap();

        // Build instruction
        if ix.args.is_empty() {
            writeln!(out, "    let instruction = {instr_type}::{variant};").unwrap();
        } else {
            writeln!(out, "    let instruction = {instr_type}::{variant} {{").unwrap();
            for arg in &ix.args {
                let name = rust_ident(&arg.name);
                writeln!(out, "        {name},").unwrap();
            }
            writeln!(out, "    }};").unwrap();
        }
        writeln!(out).unwrap();

        // Submit via tokio block_on
        writeln!(out, "    let rt = tokio::runtime::Runtime::new().map_err(|e| format!(\"tokio: {{}}\", e))?;").unwrap();
        writeln!(out, "    let tx_hash = rt.block_on(async {{").unwrap();
        writeln!(out, "        let nonces = wallet.get_accounts_nonces(signer_ids.clone()).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"nonces: {{}}\", e))?;").unwrap();
        writeln!(out, "        let mut signing_keys = Vec::new();").unwrap();
        writeln!(out, "        for sid in &signer_ids {{").unwrap();
        writeln!(out, "            let key = wallet.storage().user_data").unwrap();
        writeln!(out, "                .get_pub_account_signing_key(*sid)").unwrap();
        writeln!(out, "                .ok_or_else(|| format!(\"signing key not found for {{}}\", sid))?;").unwrap();
        writeln!(out, "            signing_keys.push(key);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        let message = Message::try_new(program_id, account_ids, nonces, instruction)").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"message: {{:?}}\", e))?;").unwrap();
        writeln!(out, "        let witness_set = WitnessSet::for_message(&message, &signing_keys);").unwrap();
        writeln!(out, "        let tx = PublicTransaction::new(message, witness_set);").unwrap();
        writeln!(out, "        wallet.sequencer_client.send_transaction(common::transaction::NSSATransaction::Public(tx)).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"submit: {{}}\", e))").unwrap();
        writeln!(out, "            .map(|r| hex::encode(r.0))").unwrap();
        writeln!(out, "    }})?;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    Ok(json!({{\"success\": true, \"tx_hash\": tx_hash}}).to_string())").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // free + version
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_free_string(s: *mut c_char) {{").unwrap();
    writeln!(out, "    if !s.is_null() {{ unsafe {{ drop(CString::from_raw(s)) }}; }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_version() -> *mut c_char {{").unwrap();
    writeln!(out, "    to_cstring(\"{}\".to_string())", idl.version).unwrap();
    writeln!(out, "}}").unwrap();

    // PDA compute helpers
    out.push_str(&generate_pda_helpers(idl));
    Ok(out)
}

/// Generate standalone PDA compute helper functions from an IDL.
///
/// Emits one `pub fn compute_{account}_pda(...)` per unique account that has
/// a `pda` field in the IDL. The generated functions use SHA-256 to combine
/// multiple seeds (matching `spel-cli/src/pda.rs` behaviour) and return an
/// `AccountId` derived from the program ID and the combined seed.
pub fn generate_pda_helpers(idl: &SpelIdl) -> String {
    use std::collections::HashSet;
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();

    for ix in &idl.instructions {
        for acc in &ix.accounts {
            let acc_name = snake_case(&acc.name);
            if let Some(pda) = &acc.pda {
                if !seen.insert(acc_name.clone()) {
                    continue; // already generated for this account name
                }

                // Collect function parameters from arg seeds.
                // Const seeds are inlined; account seeds get a TODO comment.
                let mut params: Vec<(String, String)> = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Arg { path } => {
                            let ty = ix.args.iter().find(|a| a.name == *path)
                                .map(|a| idl_type_to_rust(&a.type_))
                                .unwrap_or_else(|| "[u8; 32]".to_string());
                            // Normalise aliases to raw array types for cleaner FFI signatures
                            let param_ty = match ty.as_str() {
                                "AccountId" => "[u8; 32]".to_string(),
                                "ProgramId" => "[u32; 8]".to_string(),
                                other => other.to_string(),
                            };
                            params.push((rust_ident(path), param_ty));
                        }
                        IdlSeed::Account { .. } => {
                            // account seeds: less common, skipped (see TODO inside generated fn)
                        }
                        IdlSeed::Const { .. } => {}
                    }
                }

                // Doc comment
                writeln!(out).unwrap();
                let seed_desc: Vec<String> = pda.seeds.iter().map(|s| match s {
                    IdlSeed::Const { value } => format!("const(\"{}\")", value),
                    IdlSeed::Arg { path } => format!("arg({})", path),
                    IdlSeed::Account { path } => format!("account({})", path),
                }).collect();
                writeln!(out, "/// Compute PDA for `{}` account.", acc.name).unwrap();
                writeln!(out, "/// Seeds: [{}]", seed_desc.join(", ")).unwrap();

                // Build a type map for seed loops to look up arg types
                let param_type_map: std::collections::HashMap<String, String> =
                    params.iter().cloned().collect();

                // Function signature
                write!(out, "pub fn compute_{}_pda(", acc_name).unwrap();
                write!(out, "program_id: &ProgramId").unwrap();
                for (name, ty) in &params {
                    // Primitive scalars (u64, u32, etc.) are passed by value
                    let is_scalar = matches!(ty.as_str(), "u64" | "u32" | "u16" | "u8" | "i64" | "i32" | "i16" | "i8" | "u128" | "i128");
                    if is_scalar {
                        write!(out, ", {}: {}", name, ty).unwrap();
                    } else {
                        write!(out, ", {}: &{}", name, ty).unwrap();
                    }
                }
                writeln!(out, ") -> AccountId {{").unwrap();

                let n_seeds = pda.seeds.len();
                if n_seeds == 1 {
                    // Single seed: use directly as PdaSeed bytes
                    match &pda.seeds[0] {
                        IdlSeed::Const { value } => {
                            writeln!(out, "    let mut seed_bytes = [0u8; 32];").unwrap();
                            writeln!(out, "    let src = b\"{}\";", value).unwrap();
                            writeln!(out, "    seed_bytes[..src.len()].copy_from_slice(src);").unwrap();
                        }
                        IdlSeed::Arg { path } => {
                            let pname = rust_ident(path);
                            let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                            if arg_ty == "u64" {
                                // u64 single seed: pad little-endian bytes into [u8; 32]
                                writeln!(out, "    let mut seed_bytes = [0u8; 32];").unwrap();
                                writeln!(out, "    seed_bytes[..8].copy_from_slice(&{}.to_le_bytes());", pname).unwrap();
                            } else {
                                writeln!(out, "    let seed_bytes: [u8; 32] = *{};", pname).unwrap();
                            }
                        }
                        IdlSeed::Account { path } => {
                            let pname = rust_ident(path);
                            writeln!(out, "    // TODO: account seed '{}' — pass the raw AccountId bytes here", path).unwrap();
                            writeln!(out, "    let seed_bytes: [u8; 32] = *{};", pname).unwrap();
                        }
                    }
                    writeln!(out, "    let pda_seed = nssa_core::program::PdaSeed::new(seed_bytes);").unwrap();
                    writeln!(out, "    AccountId::from((program_id, &pda_seed))").unwrap();
                } else {
                    // Multi-seed: SHA-256(seed1 || seed2 || ...) — matches spel-cli/src/pda.rs
                    writeln!(out, "    use sha2::{{Sha256, Digest}};").unwrap();
                    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
                    for seed in &pda.seeds {
                        match seed {
                            IdlSeed::Const { value } => {
                                writeln!(out, "    {{").unwrap();
                                writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
                                writeln!(out, "        let src = b\"{}\";", value).unwrap();
                                writeln!(out, "        padded[..src.len()].copy_from_slice(src);").unwrap();
                                writeln!(out, "        hasher.update(&padded);").unwrap();
                                writeln!(out, "    }}").unwrap();
                            }
                            IdlSeed::Arg { path } => {
                                let pname = rust_ident(path);
                                let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                                if arg_ty == "u64" {
                                    // u64 seed: hash the little-endian bytes directly
                                    writeln!(out, "    hasher.update(&{}.to_le_bytes());", pname).unwrap();
                                } else {
                                    writeln!(out, "    hasher.update({} as &[u8]);", pname).unwrap();
                                }
                            }
                            IdlSeed::Account { path } => {
                                let pname = rust_ident(path);
                                writeln!(out, "    // TODO: account seed '{}' — use account bytes", path).unwrap();
                                writeln!(out, "    hasher.update({} as &[u8]);", pname).unwrap();
                            }
                        }
                    }
                    writeln!(out, "    let combined: [u8; 32] = hasher.finalize().into();").unwrap();
                    writeln!(out, "    let pda_seed = nssa_core::program::PdaSeed::new(combined);").unwrap();
                    writeln!(out, "    AccountId::from((program_id, &pda_seed))").unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
        }
    }

    out
}

/// Generate a C header file from an IDL.
pub fn generate_header(idl: &SpelIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let guard = format!("{}_FFI_H", prefix.to_uppercase());

    writeln!(out, "/* Auto-generated C header for {} FFI. DO NOT EDIT. */", idl.name).unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();

    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        writeln!(out, "/* {} instruction */", ix.name).unwrap();
        writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "void {prefix}_free_string(char* s);").unwrap();
    writeln!(out, "char* {prefix}_version(void);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#endif /* {guard} */").unwrap();

    Ok(out)
}
