//! C FFI wrapper generation from SPEL IDL.
//!
//! Generates `extern "C"` functions that accept JSON strings and return JSON strings.
//! The generated FFI includes full transaction building via `wallet::WalletCore`.
//!
//! If the IDL has `instruction_type` set (e.g. `"multisig_core::Instruction"`),
//! the generated code imports and uses that type directly — ensuring correct
//! serde/borsh representation when the instruction is sent to the zkVM guest.
//!
//! If `instruction_type` is absent, a local enum is generated with
//! `#[derive(Serialize, Deserialize)]` which works for simple programs.

use spel_framework_core::idl::*;
use std::fmt::Write;
use crate::util::*;

/// Generate C FFI wrapper source code from an IDL.
pub fn generate_ffi(idl: &SpelIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let local_enum = pascal_case(&idl.name) + "Instruction";

    // When instruction_type is set, we import it as `ProgramInstruction`.
    // When absent, we generate a local enum named `{Program}Instruction`.
    let instr_type = if idl.instruction_type.is_some() {
        "ProgramInstruction".to_string()
    } else {
        local_enum.clone()
    };

    // Header — use regular comments (//), not inner doc comments (//!), so the
    // generated file can be safely include!()'d inside a module or lib.rs.
    writeln!(out, "// Auto-generated C FFI for the {} program.", idl.name).unwrap();
    writeln!(out, "// Generated by spel-client-gen. DO NOT EDIT.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Required JSON fields for every instruction call:").unwrap();
    writeln!(out, "//   - `wallet_path`: path to NSSA wallet directory").unwrap();
    writeln!(out, "//   - `sequencer_url`: e.g. \"http://127.0.0.1:3040\"").unwrap();
    writeln!(out, "//   - `program_id_hex`: 64-char hex string identifying the program").unwrap();
    writeln!(out).unwrap();

    // Imports
    writeln!(out, "use std::ffi::{{CStr, CString}};").unwrap();
    writeln!(out, "use std::os::raw::c_char;").unwrap();
    writeln!(out, "use serde_json::{{Value, json}};").unwrap();
    writeln!(out, "use sha2::{{Sha256, Digest}};").unwrap();
    writeln!(out, "use nssa::{{AccountId, ProgramId, PublicTransaction}};").unwrap();
    writeln!(out, "use nssa::public_transaction::{{Message, WitnessSet}};").unwrap();
    writeln!(out, "use nssa_core::program::PdaSeed;").unwrap();
    writeln!(out, "use sequencer_service_rpc::RpcClient as _;").unwrap();
    writeln!(out, "use wallet::WalletCore;").unwrap();

    // Import or generate instruction type
    if let Some(ref itype) = idl.instruction_type {
        writeln!(out, "use {} as ProgramInstruction;", itype).unwrap();
    } else {
        // Generate local instruction enum
        writeln!(out, "use serde::{{Serialize, Deserialize}};").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(out, "pub enum {local_enum} {{").unwrap();
        for ix in &idl.instructions {
            let variant = pascal_case(&ix.name);
            if ix.args.is_empty() {
                writeln!(out, "    {variant},").unwrap();
            } else {
                writeln!(out, "    {variant} {{").unwrap();
                for arg in &ix.args {
                    let name = rust_ident(&arg.name);
                    let ty = idl_type_to_rust(&arg.type_);
                    writeln!(out, "        {name}: {ty},").unwrap();
                }
                writeln!(out, "    }},").unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
    }
    writeln!(out).unwrap();

    // Helper fns
    writeln!(out, "fn cstr_to_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {{").unwrap();
    writeln!(out, "    if ptr.is_null() {{ return Err(\"null pointer\".into()); }}").unwrap();
    writeln!(out, "    unsafe {{ CStr::from_ptr(ptr) }}.to_str().map_err(|e| format!(\"invalid UTF-8: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn to_cstring(s: String) -> *mut c_char {{").unwrap();
    writeln!(out, "    CString::new(s).unwrap_or_else(|_|").unwrap();
    writeln!(out, "        CString::new(r#\"{{\"success\":false,\"error\":\"null byte\"}}\"#).unwrap()").unwrap();
    writeln!(out, "    ).into_raw()").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn error_json(msg: &str) -> *mut c_char {{").unwrap();
    writeln!(out, "    let v = serde_json::json!(msg).to_string();").unwrap();
    writeln!(out, "    let body = format!(\"{{{{\\\"success\\\":false,\\\"error\\\":{{}}}}}}\", v);").unwrap();
    writeln!(out, "    to_cstring(body)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Panic-safe FFI wrapper — catches panics and returns error JSON instead of aborting.
    // AssertUnwindSafe is sound here: we consume the closure and never resume after a panic.
    writeln!(out, "fn ffi_call(f: impl FnOnce() -> Result<String, String>) -> *mut c_char {{").unwrap();
    writeln!(out, "    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {{").unwrap();
    writeln!(out, "        Ok(Ok(r))  => to_cstring(r),").unwrap();
    writeln!(out, "        Ok(Err(e)) => error_json(&e),").unwrap();
    writeln!(out, "        Err(payload) => {{").unwrap();
    writeln!(out, "            let msg = payload.downcast_ref::<&str>().copied()").unwrap();
    writeln!(out, "                .or_else(|| payload.downcast_ref::<String>().map(|s| s.as_str()))").unwrap();
    writeln!(out, "                .unwrap_or(\"<unknown panic>\");").unwrap();
    writeln!(out, "            error_json(&format!(\"panic: {{}}\", msg))").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // PDA helper — kept for potential use; all current call sites use compute_pda_with_program.
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "fn compute_pda(seeds: &[&[u8]]) -> AccountId {{").unwrap();
    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "    for seed in seeds {{").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        let len = seed.len().min(32);").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "        hasher.update(&padded);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let hash: [u8; 32] = hasher.finalize().into();").unwrap();
    writeln!(out, "    AccountId::new(hash)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // compute_pda_with_program: canonical PDA derivation used by fetch functions.
    // Matches spel_framework_core::pda::compute_pda exactly:
    //   single seed  → use padded 32-byte seed directly (no SHA-256)
    //   multi-seed   → SHA-256 of each padded 32-byte seed
    // Then derives AccountId from (program_id, PdaSeed) so PDAs are program-specific.
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "fn pda_seed_bytes(seeds: &[&[u8]]) -> Result<[u8; 32], String> {{").unwrap();
    writeln!(out, "    if seeds.is_empty() {{").unwrap();
    writeln!(out, "        return Err(\"PDA requires at least one seed\".into());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    if seeds.len() == 1 {{").unwrap();
    writeln!(out, "        let len = seeds[0].len();").unwrap();
    writeln!(out, "        if len > 32 {{ return Err(format!(\"PDA seed exceeds 32 bytes ({{len}})\")); }}").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seeds[0][..len]);").unwrap();
    writeln!(out, "        Ok(padded)").unwrap();
    writeln!(out, "    }} else {{").unwrap();
    writeln!(out, "        let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "        for seed in seeds {{").unwrap();
    writeln!(out, "            let len = seed.len();").unwrap();
    writeln!(out, "            if len > 32 {{ return Err(format!(\"PDA seed exceeds 32 bytes ({{len}})\")); }}").unwrap();
    writeln!(out, "            let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "            padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "            hasher.update(&padded);").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        Ok(hasher.finalize().into())").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "fn compute_pda_with_program(program_id: &ProgramId, seeds: &[&[u8]]) -> Result<AccountId, String> {{").unwrap();
    writeln!(out, "    Ok(AccountId::for_public_pda(program_id, &PdaSeed::new(pda_seed_bytes(seeds)?)))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_program_id_hex
    writeln!(out, "fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() != 64 {{ return Err(format!(\"program_id hex must be 64 chars, got {{}}\", s.len())); }}").unwrap();
    writeln!(out, "    let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "    let mut pid = [0u32; 8];").unwrap();
    writeln!(out, "    for (i, chunk) in bytes.chunks(4).enumerate() {{").unwrap();
    writeln!(out, "        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Ok(pid)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_program_id (alias for ProgramId-typed args)
    writeln!(out, "fn parse_program_id(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    parse_program_id_hex(s)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_account_id
    writeln!(out, "fn parse_account_id(s: &str) -> Result<AccountId, String> {{").unwrap();
    writeln!(out, "    let raw = s;\n    let s = s.strip_prefix(\"Public/\").or_else(|| s.strip_prefix(\"Private/\")).unwrap_or(s);").unwrap();
    writeln!(out, "    if let Ok(id) = s.parse() {{ return Ok(id); }}").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() == 64 {{").unwrap();
    writeln!(out, "        let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32]; arr.copy_from_slice(&bytes);").unwrap();
    writeln!(out, "        return Ok(AccountId::new(arr));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Err(format!(\"invalid AccountId: {{}}\", raw))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Shared async runtime — created once per process, reused across all FFI calls.
    writeln!(out, "static ASYNC_RUNTIME: std::sync::OnceLock<tokio::runtime::Runtime> = std::sync::OnceLock::new();").unwrap();
    writeln!(out, "fn get_runtime() -> &'static tokio::runtime::Runtime {{").unwrap();
    writeln!(out, "    ASYNC_RUNTIME.get_or_init(|| tokio::runtime::Runtime::new().expect(\"failed to create Tokio runtime\"))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Global mutex to serialise env-var mutation + wallet init across FFI threads.
    // std::env::set_var is not thread-safe on its own; all FFI entry points that
    // call init_wallet hold this lock for the duration of the mutation + WalletCore
    // construction so they cannot race on NSSA_WALLET_HOME_DIR / NSSA_SEQUENCER_URL.
    writeln!(out, "static WALLET_INIT_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn init_wallet(v: &Value) -> Result<WalletCore, String> {{").unwrap();
    writeln!(out, "    let _guard = WALLET_INIT_LOCK.lock().map_err(|_| \"wallet lock poisoned\".to_string())?;").unwrap();
    writeln!(out, "    let wallet_path = v[\"wallet_path\"].as_str().ok_or(\"missing required field: wallet_path\")?;").unwrap();
    writeln!(out, "    let sequencer_url = v[\"sequencer_url\"].as_str().ok_or(\"missing required field: sequencer_url\")?;").unwrap();
    writeln!(out, "    std::env::set_var(\"NSSA_WALLET_HOME_DIR\", wallet_path);").unwrap();
    writeln!(out, "    std::env::set_var(\"NSSA_SEQUENCER_URL\", sequencer_url);").unwrap();
    writeln!(out, "    WalletCore::from_env().map_err(|e| format!(\"wallet init: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-instruction FFI functions
    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        let variant = pascal_case(&ix.name);
        let signer_accounts: Vec<&IdlAccountItem> = ix.accounts.iter().filter(|a| a.signer).collect();

        writeln!(out, "/// FFI: {} instruction.", ix.name).unwrap();
        writeln!(out, "#[no_mangle]").unwrap();
        writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
        writeln!(out, "    let args = match cstr_to_str(args_json) {{").unwrap();
        writeln!(out, "        Ok(s) => s, Err(e) => return error_json(&e),").unwrap();
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    ffi_call(move || {fn_name}_impl(args))").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "fn {fn_name}_impl(args: &str) -> Result<String, String> {{").unwrap();
        writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
        writeln!(out, "    let program_id = parse_program_id_hex(v[\"program_id_hex\"].as_str().ok_or(\"missing program_id_hex\")?)?;").unwrap();
        writeln!(out, "    let wallet = init_wallet(&v)?;").unwrap();
        writeln!(out).unwrap();

        // Parse args
        for arg in &ix.args {
            let name = rust_ident(&arg.name);
            let parse_expr = idl_type_to_json_parse(&arg.type_, &format!("v[\"{}\"]", arg.name));
            writeln!(out, "    let {name} = {parse_expr};").unwrap();
        }
        writeln!(out).unwrap();

        // Build a type map for PDA seed arg type checks (same pattern as generate_pda_helpers)
        let param_type_map: std::collections::HashMap<String, String> = ix.args.iter()
            .map(|a| (rust_ident(&a.name), idl_type_to_rust(&a.type_)))
            .collect();

        // Resolve accounts in two passes so that PDA accounts whose seeds reference
        // other accounts (IdlSeed::Account) always find those accounts already bound.
        // Pass 1: non-PDA accounts (plain addresses and rest arrays).
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if acc.rest {
                // If there's a Vec<[u8;32]> arg, derive rest accounts from it when the
                // JSON field is absent — the UI sends keys only once (as the instruction arg).
                let src_arg = ix.args.iter().find(|a| is_vec_bytes32(&a.type_));
                if let Some(src) = src_arg {
                    let src_name = rust_ident(&src.name);
                    writeln!(out, "    let {name}: Vec<AccountId> = if v[\"{}\"].is_array() {{", acc.name).unwrap();
                    writeln!(out, "        v[\"{}\"].as_array().unwrap()", acc.name).unwrap();
                    writeln!(out, "            .iter().map(|a| parse_account_id(a.as_str().ok_or(\"expected string\")?)).collect::<Result<Vec<_>,_>>()?").unwrap();
                    writeln!(out, "    }} else {{").unwrap();
                    writeln!(out, "        {src_name}.clone()").unwrap();
                    writeln!(out, "    }};").unwrap();
                } else {
                    writeln!(out, "    let {name}: Vec<AccountId> = v[\"{}\"].as_array()", acc.name).unwrap();
                    writeln!(out, "        .ok_or(\"missing {}\")?", acc.name).unwrap();
                    writeln!(out, "        .iter().map(|a| parse_account_id(a.as_str().ok_or(\"expected string\")?)).collect::<Result<Vec<_>,_>>()?;").unwrap();
                }
            } else if acc.pda.is_none() {
                writeln!(out, "    let {name} = parse_account_id(v[\"{}\"].as_str().ok_or(\"missing {}\")?)?;",
                    acc.name, acc.name).unwrap();
            }
        }
        // Pass 2: PDA accounts (may reference accounts bound in pass 1).
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if let Some(pda) = &acc.pda {
                // Collect pre-bindings (stable buffers for types that can't be borrowed
                // as a slice element inline) and seed entries separately, then emit.
                let mut seed_pre_bindings: Vec<String> = Vec::new();
                let mut seed_entries: Vec<String> = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { value } => seed_entries.push(format!("        b\"{value}\",")),
                        IdlSeed::Account { path } => seed_entries.push(format!("        {}.as_ref(),", rust_ident(path))),
                        IdlSeed::Arg { path } => {
                            let pname = rust_ident(path);
                            let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                            match arg_ty {
                                "[u8; 32]" | "[u8;32]" | "AccountId" | "account_id" => {
                                    seed_entries.push(format!("        {pname}.as_ref(),"));
                                }
                                "[u32; 8]" | "[u32;8]" | "ProgramId" => {
                                    // collect() into a Vec to avoid a reference to a temporary
                                    seed_pre_bindings.push(format!("    let {pname}_seed_bytes: Vec<u8> = {pname}.iter().flat_map(|w| w.to_le_bytes()).collect();"));
                                    seed_entries.push(format!("        &{pname}_seed_bytes,"));
                                }
                                "u64" | "u32" | "u16" | "u8" | "i64" | "i32" | "i16" | "i8" | "u128" | "i128" => {
                                    seed_pre_bindings.push(format!("    let {pname}_seed_bytes = {pname}.to_le_bytes();"));
                                    seed_entries.push(format!("        &{pname}_seed_bytes,"));
                                }
                                "String" | "string" | "&str" => {
                                    seed_entries.push(format!("        {pname}.as_bytes(),"));
                                }
                                _ => seed_entries.push(format!("        {pname}.as_ref(),")),
                            }
                        }
                    }
                }
                for binding in &seed_pre_bindings {
                    writeln!(out, "{binding}").unwrap();
                }
                writeln!(out, "    let {name} = compute_pda_with_program(&program_id, &[").unwrap();
                for entry in &seed_entries {
                    writeln!(out, "{entry}").unwrap();
                }
                writeln!(out, "    ])?;").unwrap();
            }
        }
        writeln!(out).unwrap();

        // Build account_ids vec (non-rest accounts first, then rest)
        writeln!(out, "    let mut account_ids: Vec<AccountId> = vec![").unwrap();
        for acc in ix.accounts.iter().filter(|a| !a.rest) {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        for acc in ix.accounts.iter().filter(|a| a.rest) {
            writeln!(out, "    account_ids.extend({});", rust_ident(&acc.name)).unwrap();
        }

        // Signer IDs
        writeln!(out, "    let signer_ids: Vec<AccountId> = vec![").unwrap();
        for acc in &signer_accounts {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        writeln!(out).unwrap();

        // Build instruction
        if ix.args.is_empty() {
            writeln!(out, "    let instruction = {instr_type}::{variant};").unwrap();
        } else {
            writeln!(out, "    let instruction = {instr_type}::{variant} {{").unwrap();
            for arg in &ix.args {
                let name = rust_ident(&arg.name);
                writeln!(out, "        {name},").unwrap();
            }
            writeln!(out, "    }};").unwrap();
        }
        writeln!(out).unwrap();

        // Submit via the shared runtime
        writeln!(out, "    let rt = get_runtime();").unwrap();
        writeln!(out, "    let tx_hash = rt.block_on(async {{").unwrap();
        writeln!(out, "        let nonces = wallet.get_accounts_nonces(signer_ids.clone()).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"nonces: {{}}\", e))?;").unwrap();
        writeln!(out, "        let mut signing_keys = Vec::new();").unwrap();
        writeln!(out, "        for sid in &signer_ids {{").unwrap();
        writeln!(out, "            let key = wallet.storage().user_data").unwrap();
        writeln!(out, "                .get_pub_account_signing_key(*sid)").unwrap();
        writeln!(out, "                .ok_or_else(|| format!(\"signing key not found for {{}}\", sid))?;").unwrap();
        writeln!(out, "            signing_keys.push(key);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        let message = Message::try_new(program_id, account_ids, nonces, instruction)").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"message: {{:?}}\", e))?;").unwrap();
        writeln!(out, "        let witness_set = WitnessSet::for_message(&message, &signing_keys);").unwrap();
        writeln!(out, "        let tx = PublicTransaction::new(message, witness_set);").unwrap();
        writeln!(out, "        let raw = wallet.sequencer_client.send_transaction(common::transaction::NSSATransaction::Public(tx)).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"submit: {{}}\", e))?;").unwrap();
        writeln!(out, "        let tx_hash_hex = hex::encode(raw.0);").unwrap();
        writeln!(out, "        let poller = wallet::poller::TxPoller::new(wallet.config(), wallet.sequencer_client.clone());").unwrap();
        writeln!(out, "        poller.poll_tx(raw).await.map_err(|e| format!(\"confirm: {{}}\", e))?;").unwrap();
        writeln!(out, "        Ok::<String, String>(tx_hash_hex)").unwrap();
        writeln!(out, "    }})?;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    Ok(json!({{\"success\": true, \"tx_hash\": tx_hash}}).to_string())").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // free + version
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_free_string(s: *mut c_char) {{").unwrap();
    writeln!(out, "    if !s.is_null() {{ unsafe {{ drop(CString::from_raw(s)) }}; }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_version() -> *mut c_char {{").unwrap();
    writeln!(out, "    to_cstring(\"{}\".to_string())", idl.version).unwrap();
    writeln!(out, "}}").unwrap();

    // PDA compute helpers
    out.push_str(&generate_pda_helpers(idl));

    // Named IDL types (enums, structs) referenced by account fields
    generate_defined_types(idl, &mut out);

    // Account state structs (BorshDeserialize)
    generate_account_types(idl, &mut out);

    // Fetch functions
    generate_account_fetch_functions(idl, &prefix, &mut out);

    Ok(out)
}

/// Generate standalone PDA compute helper functions from an IDL.
///
/// Emits one `pub fn compute_{account}_pda(...)` per unique account that has
/// a `pda` field in the IDL. The generated functions use SHA-256 to combine
/// multiple seeds (matching `spel-cli/src/pda.rs` behaviour) and return an
/// `AccountId` derived from the program ID and the combined seed.
pub fn generate_pda_helpers(idl: &SpelIdl) -> String {
    use std::collections::HashSet;
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();

    for ix in &idl.instructions {
        for acc in &ix.accounts {
            let acc_name = snake_case(&acc.name);
            if let Some(pda) = &acc.pda {
                if !seen.insert(acc_name.clone()) {
                    continue; // already generated for this account name
                }

                // Collect function parameters from arg seeds.
                // Const seeds are inlined; account seeds get a TODO comment.
                let mut params: Vec<(String, String)> = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Arg { path } => {
                            let ty = ix.args.iter().find(|a| a.name == *path)
                                .map(|a| idl_type_to_rust(&a.type_))
                                .unwrap_or_else(|| "[u8; 32]".to_string());
                            // Normalise aliases to raw array types for cleaner FFI signatures
                            let param_ty = match ty.as_str() {
                                "AccountId" => "[u8; 32]".to_string(),
                                "ProgramId" => "[u32; 8]".to_string(),
                                other => other.to_string(),
                            };
                            params.push((rust_ident(path), param_ty));
                        }
                        IdlSeed::Account { .. } => {
                            // account seeds: less common, skipped (see TODO inside generated fn)
                        }
                        IdlSeed::Const { .. } => {}
                    }
                }

                // Doc comment
                writeln!(out).unwrap();
                let seed_desc: Vec<String> = pda.seeds.iter().map(|s| match s {
                    IdlSeed::Const { value } => format!("const(\"{}\")", value),
                    IdlSeed::Arg { path } => format!("arg({})", path),
                    IdlSeed::Account { path } => format!("account({})", path),
                }).collect();
                writeln!(out, "/// Compute PDA for `{}` account.", acc.name).unwrap();
                writeln!(out, "/// Seeds: [{}]", seed_desc.join(", ")).unwrap();

                // Build a type map for seed loops to look up arg types
                let param_type_map: std::collections::HashMap<String, String> =
                    params.iter().cloned().collect();

                // Function signature
                write!(out, "pub fn compute_{}_pda(", acc_name).unwrap();
                write!(out, "program_id: &ProgramId").unwrap();
                for (name, ty) in &params {
                    // Primitive scalars (u64, u32, etc.) are passed by value
                    let is_scalar = matches!(ty.as_str(), "u64" | "u32" | "u16" | "u8" | "i64" | "i32" | "i16" | "i8" | "u128" | "i128");
                    if is_scalar {
                        write!(out, ", {}: {}", name, ty).unwrap();
                    } else {
                        write!(out, ", {}: &{}", name, ty).unwrap();
                    }
                }
                writeln!(out, ") -> AccountId {{").unwrap();

                let n_seeds = pda.seeds.len();
                if n_seeds == 1 {
                    // Single seed: use directly as PdaSeed bytes
                    match &pda.seeds[0] {
                        IdlSeed::Const { value } => {
                            writeln!(out, "    let mut seed_bytes = [0u8; 32];").unwrap();
                            writeln!(out, "    let src = b\"{}\";", value).unwrap();
                            writeln!(out, "    seed_bytes[..src.len()].copy_from_slice(src);").unwrap();
                        }
                        IdlSeed::Arg { path } => {
                            let pname = rust_ident(path);
                            let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                            if arg_ty == "u64" {
                                // u64 single seed: pad little-endian bytes into [u8; 32]
                                writeln!(out, "    let mut seed_bytes = [0u8; 32];").unwrap();
                                writeln!(out, "    seed_bytes[..8].copy_from_slice(&{}.to_le_bytes());", pname).unwrap();
                            } else {
                                writeln!(out, "    let seed_bytes: [u8; 32] = *{};", pname).unwrap();
                            }
                        }
                        IdlSeed::Account { path } => {
                            let pname = rust_ident(path);
                            writeln!(out, "    // TODO: account seed '{}' — pass the raw AccountId bytes here", path).unwrap();
                            writeln!(out, "    let seed_bytes: [u8; 32] = *{};", pname).unwrap();
                        }
                    }
                    writeln!(out, "    let pda_seed = nssa_core::program::PdaSeed::new(seed_bytes);").unwrap();
                    writeln!(out, "    AccountId::for_public_pda(program_id, &pda_seed)").unwrap();
                } else {
                    // Multi-seed: SHA-256(seed1 || seed2 || ...) — matches spel-cli/src/pda.rs
                    writeln!(out, "    use sha2::{{Sha256, Digest}};").unwrap();
                    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
                    for seed in &pda.seeds {
                        match seed {
                            IdlSeed::Const { value } => {
                                writeln!(out, "    {{").unwrap();
                                writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
                                writeln!(out, "        let src = b\"{}\";", value).unwrap();
                                writeln!(out, "        padded[..src.len()].copy_from_slice(src);").unwrap();
                                writeln!(out, "        hasher.update(&padded);").unwrap();
                                writeln!(out, "    }}").unwrap();
                            }
                            IdlSeed::Arg { path } => {
                                let pname = rust_ident(path);
                                let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                                if arg_ty == "u64" {
                                    // u64 seed: hash the little-endian bytes directly
                                    writeln!(out, "    hasher.update(&{}.to_le_bytes());", pname).unwrap();
                                } else {
                                    writeln!(out, "    hasher.update({} as &[u8]);", pname).unwrap();
                                }
                            }
                            IdlSeed::Account { path } => {
                                let pname = rust_ident(path);
                                writeln!(out, "    // TODO: account seed '{}' — use account bytes", path).unwrap();
                                writeln!(out, "    hasher.update({} as &[u8]);", pname).unwrap();
                            }
                        }
                    }
                    writeln!(out, "    let combined: [u8; 32] = hasher.finalize().into();").unwrap();
                    writeln!(out, "    let pda_seed = nssa_core::program::PdaSeed::new(combined);").unwrap();
                    writeln!(out, "    AccountId::for_public_pda(program_id, &pda_seed)").unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
        }
    }

    out
}

/// Emit a JSON field expression for a given IDL type and field name.
///
/// Returns the Rust expression to use inside `serde_json::json!({...})`.
/// `u128`/`i128` must be stringified; `[u8; N]` becomes hex; Defined enum/struct types
/// are serialized via a generated match expression or nested JSON object.
fn idl_type_to_json_field(ty: &IdlType, field_name: &str, types: &[IdlTypeDef]) -> String {
    use spel_framework_core::idl::IdlType;
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "u128" | "i128" => format!("state.{field_name}.to_string()"),
            "account_id" | "AccountId" | "[u8; 32]" | "[u8;32]" => format!("hex::encode(&state.{field_name})"),
            "program_id" | "ProgramId" | "[u32; 8]" | "[u32;8]" => format!(
                "hex::encode(state.{field_name}.iter().flat_map(|w| w.to_le_bytes()).collect::<Vec<_>>())"
            ),
            _ => format!("state.{field_name}"),
        },
        IdlType::Array { array: (elem, _) } => {
            match elem.as_ref() {
                IdlType::Primitive(p) if p == "u8" => format!("hex::encode(&state.{field_name})"),
                _ => format!("state.{field_name}"),
            }
        }
        IdlType::Vec { vec } => {
            // Vec<[u8;32]> → array of hex strings; Vec<Defined(enum)> → array of strings
            match vec.as_ref() {
                IdlType::Primitive(p) if matches!(p.as_str(), "account_id" | "AccountId" | "[u8; 32]" | "[u8;32]") => {
                    format!("state.{field_name}.iter().map(hex::encode).collect::<Vec<_>>()")
                }
                IdlType::Defined { defined } => {
                    let expr = defined_type_to_json_expr(defined, "item", types);
                    format!("state.{field_name}.iter().map(|item| {expr}).collect::<Vec<_>>()")
                }
                _ => format!("state.{field_name}"),
            }
        }
        IdlType::Option { option } => {
            match option.as_ref() {
                IdlType::Defined { defined } => {
                    let expr = defined_type_to_json_expr(defined, "v", types);
                    format!("state.{field_name}.as_ref().map(|v| {expr})")
                }
                _ => format!("state.{field_name}"),
            }
        }
        IdlType::Defined { defined } => {
            defined_type_to_json_expr(defined, &format!("state.{field_name}"), types)
        }
    }
}

/// Generate a Rust expression that serializes a value of a named IDL type to a
/// `serde_json::Value` (or a type that `serde_json::json!` can embed).
///
/// For unit enums: a `match` returning `&str`.
/// For enums with fields: a `match` returning `serde_json::Value`.
/// For unknown/struct types: falls back to direct use (relies on serde).
fn defined_type_to_json_expr(type_name: &str, value_expr: &str, types: &[IdlTypeDef]) -> String {
    let Some(def) = types.iter().find(|t| t.name == type_name) else {
        return value_expr.to_string();
    };
    if def.kind != "enum" {
        return value_expr.to_string();
    }
    let all_unit = def.variants.iter().all(|v| v.fields.is_empty());
    if all_unit {
        // match &state.status { TypeName::V1 => "V1", TypeName::V2 => "V2", ... }
        let arms: String = def.variants.iter()
            .map(|v| format!("            {type_name}::{n} => \"{n}\"", n = v.name))
            .collect::<Vec<_>>()
            .join(",\n");
        format!("match &{value_expr} {{\n{arms}\n        }}")
    } else {
        // match, returning serde_json::json! per variant
        let arms: String = def.variants.iter().map(|v| {
            if v.fields.is_empty() {
                format!("            {type_name}::{n} => serde_json::json!(\"{n}\")", n = v.name)
            } else {
                let field_pats: String = v.fields.iter().map(|f| rust_ident(&f.name)).collect::<Vec<_>>().join(", ");
                let field_kvs: String = v.fields.iter().map(|f| {
                    let fname = rust_ident(&f.name);
                    let expr = match &f.type_ {
                        IdlType::Primitive(p) if matches!(p.as_str(), "account_id" | "AccountId" | "[u8; 32]" | "[u8;32]") => {
                            format!("hex::encode({fname})")
                        }
                        IdlType::Array { array: (elem, _) } if matches!(elem.as_ref(), IdlType::Primitive(p) if p == "u8") => {
                            format!("hex::encode({fname})")
                        }
                        _ => fname.clone(),
                    };
                    format!("\"{fname}\": {expr}")
                }).collect::<Vec<_>>().join(", ");
                format!(
                    "            {type_name}::{n} {{ {field_pats} }} => serde_json::json!({{\"type\": \"{n}\", {field_kvs}}})",
                    n = v.name
                )
            }
        }).collect::<Vec<_>>().join(",\n");
        format!("match &{value_expr} {{\n{arms}\n        }}")
    }
}

/// Returns true if the type (or any nested type) contains a `Defined` reference
/// that cannot be resolved in `known_types`.
fn has_unresolvable_defined_type(ty: &IdlType, known_types: &std::collections::HashSet<&str>) -> bool {
    use spel_framework_core::idl::IdlType;
    match ty {
        IdlType::Defined { defined } => !known_types.contains(defined.as_str()),
        IdlType::Vec { vec } => has_unresolvable_defined_type(vec, known_types),
        IdlType::Option { option } => has_unresolvable_defined_type(option, known_types),
        IdlType::Array { array: (elem, _) } => has_unresolvable_defined_type(elem, known_types),
        _ => false,
    }
}

/// Returns true if `acc_name` (snake_case) qualifies for fetch function generation:
/// it must have a matching struct entry in `idl.accounts` with non-empty fields and
/// all `Defined` field types resolvable in `idl.types`.
fn is_fetch_eligible(idl: &SpelIdl, acc_name: &str) -> bool {
    let known: std::collections::HashSet<&str> = idl.types.iter().map(|t| t.name.as_str()).collect();
    match idl.accounts.iter().find(|at| snake_case(&at.name) == acc_name) {
        None => false,
        Some(t) => {
            t.type_.kind == "struct"
                && !t.type_.fields.is_empty()
                && !t.type_.fields.iter().any(|f| has_unresolvable_defined_type(&f.type_, &known))
        }
    }
}

/// Emit Borsh-deserializable type definitions for all named types in `idl.types`.
/// These cover enums and structs referenced via `Defined { defined }` from account fields.
pub fn generate_defined_types(idl: &SpelIdl, out: &mut String) {
    for def in &idl.types {
        if def.name.is_empty() { continue; }
        let name = &def.name;
        writeln!(out).unwrap();
        writeln!(out, "/// Auto-generated Borsh type: `{name}`.").unwrap();
        writeln!(out, "#[allow(dead_code)]").unwrap();
        writeln!(out, "#[derive(borsh::BorshDeserialize)]").unwrap();
        if def.kind == "enum" {
            writeln!(out, "enum {name} {{").unwrap();
            for variant in &def.variants {
                if variant.fields.is_empty() {
                    writeln!(out, "    {},", variant.name).unwrap();
                } else {
                    let fields: String = variant.fields.iter()
                        .map(|f| format!("{}: {}", rust_ident(&f.name), idl_type_to_borsh_rust(&f.type_)))
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(out, "    {} {{ {fields} }},", variant.name).unwrap();
                }
            }
            writeln!(out, "}}").unwrap();
        } else if def.kind == "struct" {
            writeln!(out, "struct {name} {{").unwrap();
            for field in &def.fields {
                let fname = rust_ident(&field.name);
                let ftype = idl_type_to_borsh_rust(&field.type_);
                writeln!(out, "    pub {fname}: {ftype},").unwrap();
            }
            writeln!(out, "}}").unwrap();
        }
    }
}

/// Emit the Rust type for a struct field that will be BorshDeserialize'd.
fn idl_type_to_borsh_rust(ty: &IdlType) -> String {
    use spel_framework_core::idl::IdlType;
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "account_id" | "AccountId" | "[u8; 32]" | "[u8;32]" => "[u8; 32]".to_string(),
            "program_id" | "ProgramId" | "[u32; 8]" | "[u32;8]" => "[u32; 8]".to_string(),
            "string" => "String".to_string(),
            s => s.to_string(),
        },
        IdlType::Vec { vec } => format!("Vec<{}>", idl_type_to_borsh_rust(vec)),
        IdlType::Option { option } => format!("Option<{}>", idl_type_to_borsh_rust(option)),
        IdlType::Defined { defined } => defined.clone(),
        IdlType::Array { array: (elem, size) } => {
            format!("[{}; {}]", idl_type_to_borsh_rust(elem), size)
        }
    }
}

/// For each unique account type referenced as a PDA in any instruction, emit a
/// BorshDeserialize struct if the account type is found in `idl.accounts`.
pub fn generate_account_types(idl: &SpelIdl, out: &mut String) {
    use std::collections::HashSet;
    let mut seen: HashSet<String> = HashSet::new();

    for ix in &idl.instructions {
        for acc in &ix.accounts {
            if acc.pda.is_none() { continue; }
            let acc_name = snake_case(&acc.name);
            if !seen.insert(acc_name.clone()) { continue; }

            if !is_fetch_eligible(idl, &acc_name) { continue; }
            let type_def = idl.accounts.iter().find(|at| snake_case(&at.name) == acc_name).unwrap();

            let pascal_name = pascal_case(&acc_name);
            writeln!(out).unwrap();
            writeln!(out, "/// Auto-generated Borsh state struct for `{acc_name}` account.").unwrap();
            writeln!(out, "#[derive(borsh::BorshDeserialize)]").unwrap();
            writeln!(out, "struct {pascal_name}State {{").unwrap();
            for field in &type_def.type_.fields {
                let fname = rust_ident(&field.name);
                let ftype = idl_type_to_borsh_rust(&field.type_);
                writeln!(out, "    pub {fname}: {ftype},").unwrap();
            }
            writeln!(out, "}}").unwrap();
        }
    }
}

/// Generate `extern "C" fn {prefix}_fetch_{account}(args_json) -> *mut c_char` for each
/// unique PDA-backed account that has a known type definition.
pub fn generate_account_fetch_functions(idl: &SpelIdl, prefix: &str, out: &mut String) {
    use std::collections::HashMap;

    // Build PDA map: account_name -> (ix_index, pda) from the first instruction
    // that defines this account as a PDA. Used to generate seed-based fetch functions.
    let mut pda_map: HashMap<String, (usize, &spel_framework_core::idl::IdlPda)> = HashMap::new();
    for ix in &idl.instructions {
        for acc in &ix.accounts {
            if let Some(pda) = &acc.pda {
                let acc_name = snake_case(&acc.name);
                let ix_idx = idl.instructions.iter().position(|i| std::ptr::eq(i, ix)).unwrap_or(0);
                pda_map.entry(acc_name).or_insert((ix_idx, pda));
            }
        }
    }

    // Generate fetch functions for ALL idl.accounts entries with struct type definitions.
    for type_def in &idl.accounts {
        let acc_name = snake_case(&type_def.name);
        if type_def.type_.kind != "struct" || type_def.type_.fields.is_empty() { continue; }

        let pascal_name = pascal_case(&acc_name);
        let fn_name = format!("{prefix}_fetch_{acc_name}");

        if let Some((ix_idx, pda)) = pda_map.get(&acc_name) {
            // PDA account: compute address from seeds then fetch.
            let ix = &idl.instructions[*ix_idx];
            let param_type_map: std::collections::HashMap<String, String> = ix.args.iter()
                .map(|a| (rust_ident(&a.name), idl_type_to_rust(&a.type_)))
                .collect();

            // Determine which seeds need parse lines and which go into compute_pda args
            // (same logic as the instruction path, but using args["name"] not a bare variable)
            let mut seed_parse_lines: Vec<String> = Vec::new();
            let mut pda_seeds_code: Vec<String> = Vec::new();

            for seed in &pda.seeds {
                match seed {
                    IdlSeed::Const { value } => {
                        pda_seeds_code.push(format!("        b\"{value}\","));
                    }
                    IdlSeed::Arg { path } => {
                        let pname = rust_ident(path);
                        let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("").to_string();
                        // Parse line: read from args JSON
                        let parse_expr = idl_type_to_json_parse(&ix.args.iter().find(|a| rust_ident(&a.name) == pname)
                            .map(|a| a.type_.clone())
                            .unwrap_or(spel_framework_core::idl::IdlType::Primitive("String".to_string())),
                            &format!("args[\"{path}\"]"));
                        seed_parse_lines.push(format!("        let {pname} = {parse_expr};"));
                        // Seed bytes expression: pre-bind types that can't be safely
                        // borrowed inline (ProgramId → Vec, scalars → fixed-size array).
                        // Note: [u8;32]/AccountId args are parsed as AccountId by
                        // idl_type_to_json_parse, so .as_ref() gives a valid &[u8].
                        match arg_ty.as_str() {
                            "[u8; 32]" | "[u8;32]" | "AccountId" | "account_id" => {
                                pda_seeds_code.push(format!("        {pname}.as_ref(),"));
                            }
                            "[u32; 8]" | "[u32;8]" | "ProgramId" => {
                                seed_parse_lines.push(format!("        let {pname}_seed_bytes: Vec<u8> = {pname}.iter().flat_map(|w| w.to_le_bytes()).collect();"));
                                pda_seeds_code.push(format!("        &{pname}_seed_bytes,"));
                            }
                            "u64" | "u32" | "u16" | "u8" | "i64" | "i32" | "i16" | "i8" | "u128" | "i128" => {
                                seed_parse_lines.push(format!("        let {pname}_seed_bytes = {pname}.to_le_bytes();"));
                                pda_seeds_code.push(format!("        &{pname}_seed_bytes,"));
                            }
                            "String" | "string" | "&str" => {
                                pda_seeds_code.push(format!("        {pname}.as_bytes(),"));
                            }
                            _ => pda_seeds_code.push(format!("        {pname}.as_ref(),")),
                        }
                    }
                    IdlSeed::Account { path } => {
                        let pname = rust_ident(path);
                        // Account seeds: parse as AccountId from JSON
                        seed_parse_lines.push(format!(
                            "        let {pname} = parse_account_id(args[\"{path}\"].as_str().ok_or(\"missing {path}\")?)?;"
                        ));
                        pda_seeds_code.push(format!("        {pname}.as_ref(),"));
                    }
                }
            }

            writeln!(out).unwrap();
            writeln!(out, "/// FFI: fetch and decode `{acc_name}` account state.").unwrap();
            writeln!(out, "#[no_mangle]").unwrap();
            writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
            writeln!(out, "    ffi_call(move || {{").unwrap();
            writeln!(out, "        let args_str = match cstr_to_str(args_json) {{ Ok(s) => s.to_owned(), Err(e) => return Err(e) }};").unwrap();
            writeln!(out, "        {fn_name}_impl(&args_str)").unwrap();
            writeln!(out, "    }})").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
            writeln!(out, "fn {fn_name}_impl(args_str: &str) -> Result<String, String> {{").unwrap();
            writeln!(out, "    let args: serde_json::Value = serde_json::from_str(args_str).map_err(|e| format!(\"invalid JSON: {{e}}\"))?;").unwrap();
            writeln!(out, "    let program_id = parse_program_id_hex(args[\"program_id_hex\"].as_str().ok_or(\"missing program_id_hex\")?)?;").unwrap();
            writeln!(out, "    let wallet = init_wallet(&args)?;").unwrap();

            // Emit seed parse lines (arg and account seeds)
            for line in &seed_parse_lines {
                writeln!(out, "{line}").unwrap();
            }

            // Compute PDA — use program_id so PDAs are program-specific.
            writeln!(out, "    let pda = compute_pda_with_program(&program_id, &[").unwrap();
            for seed_line in &pda_seeds_code {
                writeln!(out, "{seed_line}").unwrap();
            }
            writeln!(out, "    ])?;").unwrap();

            // Fetch and decode
            writeln!(out, "    let rt = get_runtime();").unwrap();
            writeln!(out, "    let account = rt.block_on(async {{").unwrap();
            writeln!(out, "        wallet.sequencer_client.get_account(pda).await.map_err(|e| format!(\"get_account: {{e}}\"))").unwrap();
            writeln!(out, "    }})?;").unwrap();
            writeln!(out, "    let state = <{pascal_name}State as borsh::BorshDeserialize>::try_from_slice(&account.data).map_err(|e| format!(\"decode: {{e}}\"))?;").unwrap();

            // Build JSON response
            // Build JSON response
            writeln!(out, "    Ok(serde_json::json!({{").unwrap();
            writeln!(out, "        \"success\": true,").unwrap();
            writeln!(out, "        \"state\": {{").unwrap();
            for field in &type_def.type_.fields {
                let json_key = &field.name;
                let field_ident = rust_ident(&field.name);
                let expr = idl_type_to_json_field(&field.type_, &field_ident, &idl.types);
                writeln!(out, "            \"{json_key}\": {expr},").unwrap();
            }
            writeln!(out, "        }}").unwrap();
            writeln!(out, "    }}).to_string())").unwrap();
            writeln!(out, "}}").unwrap();
        } else {
            // Non-PDA account: caller provides the account address directly.
            writeln!(out).unwrap();
            writeln!(out, "/// FFI: fetch and decode `{acc_name}` account state by address.").unwrap();
            writeln!(out, "#[no_mangle]").unwrap();
            writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
            writeln!(out, "    ffi_call(move || {{").unwrap();
            writeln!(out, "        let args_str = match cstr_to_str(args_json) {{ Ok(s) => s.to_owned(), Err(e) => return Err(e) }};").unwrap();
            writeln!(out, "        {fn_name}_impl(&args_str)").unwrap();
            writeln!(out, "    }})").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
            writeln!(out, "fn {fn_name}_impl(args_str: &str) -> Result<String, String> {{").unwrap();
            writeln!(out, "    let args: serde_json::Value = serde_json::from_str(args_str).map_err(|e| format!(\"invalid JSON: {{e}}\"))?;").unwrap();
            writeln!(out, "    let wallet = init_wallet(&args)?;").unwrap();
            writeln!(out, "    let account_id = parse_account_id(args[\"account_id\"].as_str().ok_or(\"missing account_id\")?)?;").unwrap();
            writeln!(out, "    let rt = get_runtime();").unwrap();
            writeln!(out, "    let account = rt.block_on(async {{").unwrap();
            writeln!(out, "        wallet.sequencer_client.get_account(account_id).await.map_err(|e| format!(\"get_account: {{e}}\"))").unwrap();
            writeln!(out, "    }})?;").unwrap();
            writeln!(out, "    let state = <{pascal_name}State as borsh::BorshDeserialize>::try_from_slice(&account.data).map_err(|e| format!(\"decode: {{e}}\"))?;").unwrap();
            writeln!(out, "    Ok(serde_json::json!({{").unwrap();
            writeln!(out, "        \"success\": true,").unwrap();
            writeln!(out, "        \"state\": {{").unwrap();
            for field in &type_def.type_.fields {
                let json_key = &field.name;
                let field_ident = rust_ident(&field.name);
                let expr = idl_type_to_json_field(&field.type_, &field_ident, &idl.types);
                writeln!(out, "            \"{json_key}\": {expr},").unwrap();
            }
            writeln!(out, "        }}").unwrap();
            writeln!(out, "    }}).to_string())").unwrap();
            writeln!(out, "}}").unwrap();
        }
    }
}

/// Generate a C header file from an IDL.
pub fn generate_header(idl: &SpelIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let guard = format!("{}_FFI_H", prefix.to_uppercase());

    writeln!(out, "/* Auto-generated C header for {} FFI. DO NOT EDIT. */", idl.name).unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();

    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        writeln!(out, "/* {} instruction */", ix.name).unwrap();
        writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
        writeln!(out).unwrap();
    }

    // Fetch function declarations for PDA-backed accounts.
    // Only emit a declaration if there is a matching accounts[] entry with kind == "struct"
    // and non-empty fields — mirroring the guard used in generate_account_fetch_functions.
    {
        use std::collections::HashSet;
        let mut seen: HashSet<String> = HashSet::new();
        for ix in &idl.instructions {
            for acc in &ix.accounts {
                if acc.pda.is_some() {
                    let acc_name = snake_case(&acc.name);
                    if !seen.insert(acc_name.clone()) {
                        continue;
                    }
                    if !is_fetch_eligible(idl, &acc_name) { continue; }

                    let fn_name = format!("{}_fetch_{}", prefix, acc_name);
                    writeln!(out, "/* fetch {} account state */", acc.name).unwrap();
                    writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
                    writeln!(out).unwrap();
                }
            }
        }
    }

    writeln!(out, "void {prefix}_free_string(char* s);").unwrap();
    writeln!(out, "char* {prefix}_version(void);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#endif /* {guard} */").unwrap();

    Ok(out)
}
